name: supplier_mobile
description: Supreme & Palace Bot.
publish_to: "none"
version: 0.5.5+5

environment:
  sdk: ">=2.8.0 <3.0.0"

flutter_icons:
  image_path_android: "assets/icons/launcher.png"
  image_path_ios: "assets/icons/launcher.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icons/launcher_foreground.png"
  adaptive_icon_background: "#1B191C"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  auto_route: ^0.6.9
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  dartz: ^0.9.2
  dio: ^3.0.10
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.1
  flutter_form_builder: ^4.2.0
  flutter_hooks: ^0.15.0
  flutter_secure_storage: ^3.3.5
  flutter_typeahead: <=1.9.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  hive: ^1.4.4+1
  hydrated_bloc: ^6.1.0
  injectable: ^1.0.7
  jiffy: ^3.0.1
  json_annotation: ^3.1.1
  path_provider: ^1.6.27
  rxdart: ^0.25.0
  url_launcher: ^5.7.10
  uuid: ^2.2.2
  flutter_inappwebview: ^5.1.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.1
  freezed: ^0.12.7
  flutter_launcher_icons: ^0.8.1
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  lint: ^1.3.0

dependency_overrides:
  intl: ^0.17.0
  date_range_picker:
    git:
      url: https://github.com/ingmferrer/date_range_picker.git

flutter:
  uses-material-design: true

  assets:
    - assets/javascript/supremeInject.js

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
