const progressMap = <String, double>{
  'Item no longer available': 0,
  'Waiting for restock': 0,
  'Loading page': 0.1,
  'Waiting for product': 0.2,
  'Product found': 0.3,
  'Loading product details': 0.4,
  'Adding to cart': 0.5,
  'Loading checkout': 0.6,
  'Checkout autofill': 0.7,
  'Checkout delay': 0.75,
  'Waiting for response': 0.8,
  'Waiting for captcha': 0.8,
  'Processing (1)': 0.85,
  'Processing (2)': 0.9,
  'Processing (3)': 0.925,
  'Processing (4)': 0.95,
  'Processing (5)': 0.975,
  'Processing (x)': 0.975,
  'Success': 1,
  'Duplicate order': 0,
  'Blacklisted': 0,
  'Sold out': 0,
  'Card decline': 0,
};
